### ISSUE TITLE
Bug in AIOLunarSpells and its fix

### ISSUE THREAD

**Issue by forrez9** [BigAussie/BigAussie#1]
There is a bug in the script that after doing a birdhouse run, the "take X out of bank" quantity is set to 40 after taking out 40 seeds, but the cached value for what this X is, is still a whatever the script is using before the birdhouse run. I made a simple fix for this by slightly changing the Run function at line 1798 to include these lines:

if BIRDHOUSEENABLED and BirdHouseRunner.CanDoBirdHouseRun() then
    **begin**
        BirdHouseRunner.DoBirdHouseRun();
	**Bank.CachedQuantity := 40;**
    **end;**

Just thought I'd let you know so you can put it in your next version :)

**Comment by BigAussie** [comment]
Applied this in rev 24, appreciate the help <3
